name: Android FOSS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant Execute Permission for Gradle
      run: chmod +x gradlew
      continue-on-error: true

    - name: Create local.properties with Android SDK path
      run: echo "sdk.dir=$ANDROID_HOME" > local.properties

    # കാണാതായ ഡീബഗ് കീസ്റ്റോർ ഫയൽ തനിയെ നിർമ്മിക്കാനുള്ള പുതിയ വരി:
    - name: Setup Default Debug Keystore
      run: |
        mkdir -p ~/.android
        keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

    - name: Build FOSS Debug APK
      run: gradle assembleDebug
